service: myService

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 3 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true

functions:
  hello:
    handler: index.handler # required, handler set in AWS Lambda
